repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
{%- if cookiecutter.use_black == 'y' -%}
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
{%- endif %}
{%- if cookiecutter.pylint == 'y' -%}
-   repo: https://github.com/PyCQA/pylint
    rev: v2.12.2
    hooks:
    -   id: pylint
{%- endif %}
{%- if cookiecutter.use_isort == 'y' -%}
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
{%- endif %}
{%- if cookiecutter.use_mypy == 'y' -%}
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
{%- endif %}
{%- if cookiecutter.use_radon == 'y' -%}
-   repo: https://github.com/yunojuno/pre-commit-xenon
    rev: v0.1
    hooks:
    - id: xenon
      args: ["--max-average=A", "--max-modules=C", "--max-absolute=C"]
{%- endif %}
